# Autogenerated config.py
# Documentation:
#   qute://help/configuring.html
#   qute://help/settings.html

# Uncomment this to still load settings configured via autoconfig.yml
# config.load_autoconfig()

c.colors.completion.category.bg = '#4a90d9'
c.colors.completion.category.border.top = '#4a90d9'
c.colors.completion.category.border.bottom = '#4a90d9'
c.colors.completion.category.fg = '#2e3436'
c.colors.completion.even.bg = '#ededed'
c.colors.completion.odd.bg = '#ededed'
c.colors.completion.fg = '#2e3436'
c.colors.completion.match.fg = '#a52a2a'
c.colors.completion.item.selected.bg = '#a5a5a1'
c.colors.completion.item.selected.border.top = '#a5a5a1'
c.colors.completion.item.selected.border.bottom = '#a5a5a1'
c.colors.completion.item.selected.fg = '#2e3436'

c.colors.prompts.bg = '#ededed'
c.colors.prompts.border = '0px'
c.colors.prompts.fg = '#2e3436'
c.colors.prompts.selected.bg = '#a5a5a1'

c.colors.statusbar.command.bg = '#ededed'
c.colors.statusbar.command.fg = '#2e3436'
c.colors.statusbar.command.private.bg = '#2e3436'
c.colors.statusbar.command.private.fg = '#EDEDED'
c.colors.statusbar.insert.bg = '#ededed'
c.colors.statusbar.insert.fg = '#2e3436'
c.colors.statusbar.normal.bg = '#ededed'
c.colors.statusbar.normal.fg = '#2e3436'
c.colors.statusbar.private.bg = '#2e3436'
c.colors.statusbar.private.fg = '#ededed'
c.colors.statusbar.progress.bg = '#2e3436'
c.colors.statusbar.url.error.fg = '#A52A2A'
c.colors.statusbar.url.fg = '#2e3436'
c.colors.statusbar.url.hover.fg = '#0084c8'
c.colors.statusbar.url.success.http.fg = '#2e3436'
c.colors.statusbar.url.success.https.fg = '#4e9a06'
c.colors.statusbar.url.warn.fg = '#ce5c00'

c.completion.scrollbar.width = 0

c.editor.command = ['emacsclient', '-c', '{}']

c.fonts.completion.category = 'bold 9pt sans'
c.fonts.completion.entry = '9pt sans'
c.fonts.downloads = '9pt sans'
c.fonts.messages.error = '9pt sans'
c.fonts.messages.info = '9pt sans'
c.fonts.messages.warning = '9pt sans'
c.fonts.monospace = 'monospace'
c.fonts.prompts = '9pt sans'
c.fonts.statusbar = '9pt sans'

c.tabs.show = 'never'
c.tabs.tabs_are_windows = True

c.url.start_pages = 'about:blank'
c.url.searchengines = {"DEFAULT" : "https://encrypted.google.com/search?q={}"}
